export enum USER_ACTION_TYPES {
  UPDATE_USER = 'UPDATE_USER'
}

export enum TODO_ACTION_TYPES {
  TOGGLE_TODO_STATUS = 'UPDATE_TODO_STATUS',
  ADD_TODO = 'ADD_TODO',
  CLEAR_COMPLETED = 'CLEAR_COMPLETED'
}
